/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.acme.fnol.process.api.fnol_process_api.api;


import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.acme.fnol.process.api.fnol_process_api.model.Claim;


import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-01-03T23:47:43.320Z")

@Api(value = "fnol", description = "the fnol API")
public interface FnolApi {

    @ApiOperation(value = "Add the first notice of loss", nickname = "addFirstNoticeOfLoss", notes = "Create a First Notice of Loss", response = Claim.class, tags={ "admins", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Claim created", response = Claim.class),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 409, message = "an existing claim already exists") })
    @RequestMapping(value = "/fnol",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Claim> addFirstNoticeOfLoss(@ApiParam(value = "Inventory item to add"  )  @Valid @RequestBody Claim claim);


    @ApiOperation(value = "Get First Notice of Loss", nickname = "searchInventory", notes = "By passing in the appropriate options, you can search for available fnol in the system ", response = Claim.class, responseContainer = "List", tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "search results matching criteria", response = Claim.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/fnol",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Claim>> searchInventory(@ApiParam(value = "pass an optional search string for looking up claim id") @Valid @RequestParam(value = "claimid", required = false) String claimid);

}
